title: HalfAirの导航
description: 个人网络导航站
author: HalfAir
favicon: favicon.ico
logo_text: 导航站

fonts:
  title:
    family: Poppins
    weight: 600
    source: google
  subtitle:
    family: Quicksand
    weight: 500
    source: google
  body:
    family: Noto Sans SC
    weight: 400
    source: google
    
profile:
  title: Hello,
  subtitle: Welcome to My Navigation
  description: 导航菜单

social:
  - name: GitHub
    url: https://github.com/QAQ-AWA
    icon: fab fa-github
  - name: Bilibili
    url: https://space.bilibili.com/642345080
    icon: fa-brands fa-bilibili